version: '3.8'

x-logging-default: &logging-default
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  keystore:
    image: elasticsearch:${ELK_VERSION}
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /setup/setup-keystore.sh
    user: "0"
    volumes:
        - ./elk/secrets:/secrets
        - ./elk/setup/:/setup/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    logging: *logging-default

  certs:
    image: elasticsearch:${ELK_VERSION}
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /setup/setup-certs.sh
    user: "0"
    volumes:
      - ./elk/secrets:/secrets
      - ./elk/setup/:/setup
    logging: *logging-default
