import views.main.categories.cosmetics.subcategories.cosmetics_aroma as cosmetics_aroma
import views.main.categories.cosmetics.subcategories.cosmetics_cleaning_products as cosmetics_cleaning_products
import views.main.categories.cosmetics.subcategories.cosmetics_deodorants as cosmetics_deodorants
import views.main.categories.cosmetics.subcategories.cosmetics_eye as cosmetics_eye
import views.main.categories.cosmetics.subcategories.cosmetics_lips as cosmetics_lips
import views.main.categories.cosmetics.subcategories.cosmetics_mochalki as cosmetics_mochalki
import views.main.categories.cosmetics.subcategories.cosmetics_nails as cosmetics_nails
import views.main.categories.cosmetics.subcategories.cosmetics_rascheski as cosmetics_rascheski
import views.main.categories.cosmetics.subcategories.cosmetics_salt_bomb as cosmetics_salt_bomb
import views.main.categories.cosmetics.subcategories.cosmetics_the_rest_hair as cosmetics_the_rest_hair
import views.main.categories.cosmetics.subcategories.cosmetics_tooth as cosmetics_tooth
import views.main.categories.cosmetics.subcategories.cosmetics_toilet_paper as cosmetics_toilet_paper
import views.main.categories.cosmetics.subcategories.cosmetics_tweezers as cosmetics_tweezers
import views.main.categories.cosmetics.subcategories.decor_ukhod as decor_ukhod
import views.main.categories.cosmetics.subcategories.razor_blades_and_cassettes as razor_blades_and_cassettes


SUBCATEGORY_CONFIG = {
    decor_ukhod.SUBCATEGORY_SLUG: {
        "slug": decor_ukhod.SUBCATEGORY_SLUG,
        "title": decor_ukhod.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics.svg",
        "category_code": decor_ukhod.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": decor_ukhod.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": decor_ukhod.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": decor_ukhod.NOMINAL_QUANTITY_TYPES,
        "product_types": decor_ukhod.PRODUCT_TYPES,
        "usage_term_types": decor_ukhod.USAGE_TERM_TYPES,
        "content_type_choices": decor_ukhod.CONTENT_TYPE_CHOICES,
        "for_children_choices": decor_ukhod.FOR_CHILDREN_CHOICES,
        "default_countries": decor_ukhod.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": decor_ukhod.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_aroma.SUBCATEGORY_SLUG: {
        "slug": cosmetics_aroma.SUBCATEGORY_SLUG,
        "title": cosmetics_aroma.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_aroma.svg",
        "category_code": cosmetics_aroma.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_aroma.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_aroma.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_aroma.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_aroma.PRODUCT_TYPES,
        "usage_term_types": cosmetics_aroma.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_aroma.CONTENT_TYPE_CHOICES,
        "for_children_choices": cosmetics_aroma.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_aroma.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_aroma.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_cleaning_products.SUBCATEGORY_SLUG: {
        "slug": cosmetics_cleaning_products.SUBCATEGORY_SLUG,
        "title": cosmetics_cleaning_products.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_cleaning_products.svg",
        "category_code": cosmetics_cleaning_products.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_cleaning_products.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_cleaning_products.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_cleaning_products.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_cleaning_products.PRODUCT_TYPES,
        "usage_term_types": cosmetics_cleaning_products.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_cleaning_products.CONTENT_TYPE_CHOICES,
        "for_children_choices": cosmetics_cleaning_products.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_cleaning_products.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_cleaning_products.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_deodorants.SUBCATEGORY_SLUG: {
        "slug": cosmetics_deodorants.SUBCATEGORY_SLUG,
        "title": cosmetics_deodorants.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_deodorants.svg",
        "category_code": cosmetics_deodorants.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_deodorants.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_deodorants.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_deodorants.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_deodorants.PRODUCT_TYPES,
        "usage_term_types": cosmetics_deodorants.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_deodorants.CONTENT_TYPE_CHOICES,
        "for_children_choices": cosmetics_deodorants.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_deodorants.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_deodorants.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_tooth.SUBCATEGORY_SLUG: {
        "slug": cosmetics_tooth.SUBCATEGORY_SLUG,
        "title": cosmetics_tooth.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_tooth.svg",
        "category_code": cosmetics_tooth.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_tooth.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_tooth.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_tooth.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_tooth.PRODUCT_TYPES,
        "usage_term_types": cosmetics_tooth.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_tooth.CONTENT_TYPE_CHOICES,
        "for_children_choices": cosmetics_tooth.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_tooth.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_tooth.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
        "tnved_codes_by_product_type": cosmetics_tooth.TNVED_CODES_BY_PRODUCT_TYPE,
        "category_code_by_tnved": cosmetics_tooth.CATEGORY_CODE_BY_TNVED,
        "content_type_trigger_tnved_codes": cosmetics_tooth.CONTENT_TYPE_TRIGGER_TNVED_CODES,
        "content_type_trigger_product_types": cosmetics_tooth.CONTENT_TYPE_TRIGGER_PRODUCT_TYPES,
        "content_label_by_tnved": cosmetics_tooth.CONTENT_LABEL_BY_TNVED,
        "content_label_by_product_type": cosmetics_tooth.CONTENT_LABEL_BY_PRODUCT_TYPE,
        "default_content_label": cosmetics_tooth.DEFAULT_CONTENT_LABEL,
    },
    cosmetics_eye.SUBCATEGORY_SLUG: {
        "slug": cosmetics_eye.SUBCATEGORY_SLUG,
        "title": cosmetics_eye.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_eye.svg",
        "category_code": cosmetics_eye.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_eye.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_eye.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_eye.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_eye.PRODUCT_TYPES,
        "usage_term_types": cosmetics_eye.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_eye.CONTENT_TYPE_CHOICES,
        "for_children_choices": cosmetics_eye.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_eye.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_eye.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_lips.SUBCATEGORY_SLUG: {
        "slug": cosmetics_lips.SUBCATEGORY_SLUG,
        "title": cosmetics_lips.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_lips.svg",
        "category_code": cosmetics_lips.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_lips.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_lips.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_lips.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_lips.PRODUCT_TYPES,
        "usage_term_types": cosmetics_lips.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_lips.CONTENT_TYPE_CHOICES,
        "for_children_choices": cosmetics_lips.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_lips.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_lips.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_mochalki.SUBCATEGORY_SLUG: {
        "slug": cosmetics_mochalki.SUBCATEGORY_SLUG,
        "title": cosmetics_mochalki.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_mochalki.svg",
        "category_code": cosmetics_mochalki.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_mochalki.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_mochalki.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_mochalki.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_mochalki.PRODUCT_TYPES,
        "usage_term_types": cosmetics_mochalki.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_mochalki.CONTENT_TYPE_CHOICES,
        "content_type_enabled": cosmetics_mochalki.CONTENT_TYPE_ENABLED,
        "default_content_label": cosmetics_mochalki.DEFAULT_CONTENT_LABEL,
        "export_has_material_field": True,
        "export_has_children_field": True,
        "for_children_choices": cosmetics_mochalki.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_mochalki.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_mochalki.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_nails.SUBCATEGORY_SLUG: {
        "slug": cosmetics_nails.SUBCATEGORY_SLUG,
        "title": cosmetics_nails.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_nails.svg",
        "category_code": cosmetics_nails.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_nails.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_nails.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_nails.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_nails.PRODUCT_TYPES,
        "usage_term_types": cosmetics_nails.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_nails.CONTENT_TYPE_CHOICES,
        "for_children_choices": cosmetics_nails.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_nails.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_nails.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
        "tnved_codes_by_product_type": cosmetics_nails.TNVED_CODES_BY_PRODUCT_TYPE,
        "category_code_by_tnved": cosmetics_nails.CATEGORY_CODE_BY_TNVED,
        "content_type_trigger_tnved_codes": cosmetics_nails.CONTENT_TYPE_TRIGGER_TNVED_CODES,
        "content_type_trigger_product_types": cosmetics_nails.CONTENT_TYPE_TRIGGER_PRODUCT_TYPES,
        "content_label_by_tnved": cosmetics_nails.CONTENT_LABEL_BY_TNVED,
        "content_label_by_product_type": cosmetics_nails.CONTENT_LABEL_BY_PRODUCT_TYPE,
        "default_content_label": cosmetics_nails.DEFAULT_CONTENT_LABEL,
        "complectation_trigger_product_types": cosmetics_nails.COMPLECTATION_TRIGGER_PRODUCT_TYPES,
        "complectation_trigger_tnved_codes": cosmetics_nails.COMPLECTATION_TRIGGER_TNVED_CODES,
        "service_life_trigger_product_types": cosmetics_nails.SERVICE_LIFE_TRIGGER_PRODUCT_TYPES,
        "service_life_trigger_tnved_codes": cosmetics_nails.SERVICE_LIFE_TRIGGER_TNVED_CODES,
    },
    cosmetics_rascheski.SUBCATEGORY_SLUG: {
        "slug": cosmetics_rascheski.SUBCATEGORY_SLUG,
        "title": cosmetics_rascheski.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_rascheski.svg",
        "category_code": cosmetics_rascheski.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_rascheski.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_rascheski.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_rascheski.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_rascheski.PRODUCT_TYPES,
        "usage_term_types": cosmetics_rascheski.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_rascheski.CONTENT_TYPE_CHOICES,
        "content_type_enabled": cosmetics_rascheski.CONTENT_TYPE_ENABLED,
        "default_content_label": cosmetics_rascheski.DEFAULT_CONTENT_LABEL,
        "export_has_material_field": True,
        "export_has_children_field": True,
        "for_children_choices": cosmetics_rascheski.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_rascheski.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_rascheski.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_salt_bomb.SUBCATEGORY_SLUG: {
        "slug": cosmetics_salt_bomb.SUBCATEGORY_SLUG,
        "title": cosmetics_salt_bomb.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_salt_bomb.svg",
        "category_code": cosmetics_salt_bomb.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_salt_bomb.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_salt_bomb.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_salt_bomb.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_salt_bomb.PRODUCT_TYPES,
        "usage_term_types": cosmetics_salt_bomb.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_salt_bomb.CONTENT_TYPE_CHOICES,
        "for_children_choices": cosmetics_salt_bomb.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_salt_bomb.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_salt_bomb.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_the_rest_hair.SUBCATEGORY_SLUG: {
        "slug": cosmetics_the_rest_hair.SUBCATEGORY_SLUG,
        "title": cosmetics_the_rest_hair.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/the_rest_hair_cosmetics.svg",
        "category_code": cosmetics_the_rest_hair.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_the_rest_hair.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_the_rest_hair.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_the_rest_hair.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_the_rest_hair.PRODUCT_TYPES,
        "usage_term_types": cosmetics_the_rest_hair.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_the_rest_hair.CONTENT_TYPE_CHOICES,
        "for_children_choices": cosmetics_the_rest_hair.FOR_CHILDREN_CHOICES,
        "default_countries": cosmetics_the_rest_hair.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_the_rest_hair.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_toilet_paper.SUBCATEGORY_SLUG: {
        "slug": cosmetics_toilet_paper.SUBCATEGORY_SLUG,
        "title": cosmetics_toilet_paper.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_toilet_paper.svg",
        "category_code": cosmetics_toilet_paper.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_toilet_paper.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_toilet_paper.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_toilet_paper.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_toilet_paper.PRODUCT_TYPES,
        "usage_term_types": cosmetics_toilet_paper.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_toilet_paper.CONTENT_TYPE_CHOICES,
        "content_type_enabled": cosmetics_toilet_paper.CONTENT_TYPE_ENABLED,
        "content_value_enabled": cosmetics_toilet_paper.CONTENT_VALUE_ENABLED,
        "default_content_label": cosmetics_toilet_paper.DEFAULT_CONTENT_LABEL,
        "export_has_material_field": True,
        "export_has_children_field": True,
        "export_has_layers_field": True,
        "for_children_choices": cosmetics_toilet_paper.FOR_CHILDREN_CHOICES,
        "for_children_enabled": cosmetics_toilet_paper.FOR_CHILDREN_ENABLED,
        "default_countries": cosmetics_toilet_paper.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_toilet_paper.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "layers_characteristic_choices": cosmetics_toilet_paper.LAYERS_CHARACTERISTIC_CHOICES,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    cosmetics_tweezers.SUBCATEGORY_SLUG: {
        "slug": cosmetics_tweezers.SUBCATEGORY_SLUG,
        "title": cosmetics_tweezers.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_tweezers.svg",
        "category_code": cosmetics_tweezers.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": cosmetics_tweezers.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": cosmetics_tweezers.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": cosmetics_tweezers.NOMINAL_QUANTITY_TYPES,
        "product_types": cosmetics_tweezers.PRODUCT_TYPES,
        "usage_term_types": cosmetics_tweezers.USAGE_TERM_TYPES,
        "content_type_choices": cosmetics_tweezers.CONTENT_TYPE_CHOICES,
        "content_type_enabled": cosmetics_tweezers.CONTENT_TYPE_ENABLED,
        "content_value_enabled": cosmetics_tweezers.CONTENT_VALUE_ENABLED,
        "default_content_label": cosmetics_tweezers.DEFAULT_CONTENT_LABEL,
        "export_has_material_field": True,
        "export_has_children_field": False,
        "for_children_choices": cosmetics_tweezers.FOR_CHILDREN_CHOICES,
        "for_children_enabled": cosmetics_tweezers.FOR_CHILDREN_ENABLED,
        "default_countries": cosmetics_tweezers.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": cosmetics_tweezers.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/decor_ukhod/2nd_step.html",
        "step_3_template": "helpers/cosmetics/decor_ukhod/3rd_step.html",
    },
    razor_blades_and_cassettes.SUBCATEGORY_SLUG: {
        "slug": razor_blades_and_cassettes.SUBCATEGORY_SLUG,
        "title": razor_blades_and_cassettes.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/cosmetics_razor.svg",
        "category_code": razor_blades_and_cassettes.SUBCATEGORY_CATEGORY_CODE,
        "allowed_tnved_codes": razor_blades_and_cassettes.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": razor_blades_and_cassettes.ALLOWED_TNVED_CHOICES,
        "nominal_quantity_types": razor_blades_and_cassettes.NOMINAL_QUANTITY_TYPES,
        "product_types": razor_blades_and_cassettes.PRODUCT_TYPES,
        "usage_term_types": razor_blades_and_cassettes.USAGE_TERM_TYPES,
        "content_type_choices": razor_blades_and_cassettes.CONTENT_TYPE_CHOICES,
        "content_type_enabled": razor_blades_and_cassettes.CONTENT_TYPE_ENABLED,
        "content_value_enabled": razor_blades_and_cassettes.CONTENT_VALUE_ENABLED,
        "for_children_choices": razor_blades_and_cassettes.FOR_CHILDREN_CHOICES,
        "default_countries": razor_blades_and_cassettes.DEFAULT_COUNTRIES,
        "nominal_quantity_types_by_product_type": razor_blades_and_cassettes.NOMINAL_QUANTITY_TYPES_BY_PRODUCT_TYPE,
        "step_2_template": "helpers/cosmetics/razor_blades_and_cassettes/2nd_step.html",
        "step_3_template": "helpers/cosmetics/razor_blades_and_cassettes/3rd_step.html",
        "complectation_trigger_product_types": razor_blades_and_cassettes.COMPLECTATION_TRIGGER_PRODUCT_TYPES,
        "complectation_trigger_tnved_codes": razor_blades_and_cassettes.COMPLECTATION_TRIGGER_TNVED_CODES,
        "tnved_codes_by_product_type": razor_blades_and_cassettes.TNVED_CODES_BY_PRODUCT_TYPE,
        "category_code_by_tnved": razor_blades_and_cassettes.CATEGORY_CODE_BY_TNVED,
        "standard_tnved_codes_by_product_type": razor_blades_and_cassettes.STANDARD_TNVED_CODES_BY_PRODUCT_TYPE,
        "replaceable_razor_tnved_code": razor_blades_and_cassettes.REPLACEABLE_RAZOR_TNVED_CODE,
        "standard_razor_product_types": razor_blades_and_cassettes.STANDARD_RAZOR_PRODUCT_TYPES,
        "replaceable_razor_product_types": razor_blades_and_cassettes.REPLACEABLE_RAZOR_PRODUCT_TYPES,
    },
}


def get_subcategory_config(subcategory: str | None) -> dict | None:
    if not subcategory:
        return None
    return SUBCATEGORY_CONFIG.get(subcategory)
