import views.main.categories.toys.subcategories.doll_accessories as doll_accessories
import views.main.categories.toys.subcategories.puzzles as puzzles
import views.main.categories.toys.subcategories.competition_cars as competition_cars
import views.main.categories.toys.subcategories.sets_kits as sets_kits
import views.main.categories.toys.subcategories.motorized_toys as motorized_toys
import views.main.categories.toys.subcategories.animal_creature as animal_creature
import views.main.categories.toys.subcategories.scale_models_other as scale_models_other


SUBCATEGORY_CONFIG = {
    doll_accessories.SUBCATEGORY_SLUG: {
        "slug": doll_accessories.SUBCATEGORY_SLUG,
        "title": doll_accessories.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/toys/doll_accessories.png",
        "category_code": doll_accessories.SUBCATEGORY_CATEGORY_CODE,
        "category_code_by_tnved": doll_accessories.CATEGORY_CODE_BY_TNVED,
        "allowed_tnved_codes": doll_accessories.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": doll_accessories.ALLOWED_TNVED_CHOICES,
        "allowed_tnved_codes_by_product_type": doll_accessories.ALLOWED_TNVED_CODES_BY_PRODUCT_TYPE,
        "okpd2_choices_by_tnved": doll_accessories.OKPD2_CHOICES_BY_TNVED,
        "model_article_types": doll_accessories.MODEL_ARTICLE_TYPES,
        "product_types": doll_accessories.PRODUCT_TYPES,
        "material_choices": doll_accessories.MATERIAL_CHOICES,
        "min_child_age_choices": doll_accessories.MIN_CHILD_AGE_CHOICES,
        "usage_term_types": doll_accessories.USAGE_TERM_TYPES,
        "service_life_types": doll_accessories.SERVICE_LIFE_TYPES,
        "default_countries": doll_accessories.DEFAULT_COUNTRIES,
        "step_2_template": "helpers/toys/doll_accessories/2nd_step.html",
        "step_3_template": "helpers/toys/doll_accessories/3rd_step.html",
    },
    puzzles.SUBCATEGORY_SLUG: {
        "slug": puzzles.SUBCATEGORY_SLUG,
        "title": puzzles.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/toys/puzzles.png",
        "icon_class": "toys-category-icon--puzzles",
        "category_code": puzzles.SUBCATEGORY_CATEGORY_CODE,
        "category_code_by_tnved": puzzles.CATEGORY_CODE_BY_TNVED,
        "allowed_tnved_codes": puzzles.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": puzzles.ALLOWED_TNVED_CHOICES,
        "allowed_tnved_codes_by_product_type": puzzles.ALLOWED_TNVED_CODES_BY_PRODUCT_TYPE,
        "okpd2_choices_by_tnved": puzzles.OKPD2_CHOICES_BY_TNVED,
        "model_article_types": puzzles.MODEL_ARTICLE_TYPES,
        "product_types": puzzles.PRODUCT_TYPES,
        "material_choices": puzzles.MATERIAL_CHOICES,
        "min_child_age_choices": puzzles.MIN_CHILD_AGE_CHOICES,
        "usage_term_types": puzzles.USAGE_TERM_TYPES,
        "service_life_types": puzzles.SERVICE_LIFE_TYPES,
        "default_countries": puzzles.DEFAULT_COUNTRIES,
        "step_2_template": "helpers/toys/doll_accessories/2nd_step.html",
        "step_3_template": "helpers/toys/doll_accessories/3rd_step.html",
    },
    competition_cars.SUBCATEGORY_SLUG: {
        "slug": competition_cars.SUBCATEGORY_SLUG,
        "title": competition_cars.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/toys/competition_cars.png",
        "icon_class": "toys-category-icon--competition-cars",
        "category_code": competition_cars.SUBCATEGORY_CATEGORY_CODE,
        "category_code_by_tnved": competition_cars.CATEGORY_CODE_BY_TNVED,
        "allowed_tnved_codes": competition_cars.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": competition_cars.ALLOWED_TNVED_CHOICES,
        "allowed_tnved_codes_by_product_type": competition_cars.ALLOWED_TNVED_CODES_BY_PRODUCT_TYPE,
        "okpd2_choices_by_tnved": competition_cars.OKPD2_CHOICES_BY_TNVED,
        "model_article_types": competition_cars.MODEL_ARTICLE_TYPES,
        "product_types": competition_cars.PRODUCT_TYPES,
        "material_choices": competition_cars.MATERIAL_CHOICES,
        "min_child_age_choices": competition_cars.MIN_CHILD_AGE_CHOICES,
        "usage_term_types": competition_cars.USAGE_TERM_TYPES,
        "service_life_types": competition_cars.SERVICE_LIFE_TYPES,
        "default_countries": competition_cars.DEFAULT_COUNTRIES,
        "step_2_template": "helpers/toys/doll_accessories/2nd_step.html",
        "step_3_template": "helpers/toys/doll_accessories/3rd_step.html",
    },
    sets_kits.SUBCATEGORY_SLUG: {
        "slug": sets_kits.SUBCATEGORY_SLUG,
        "title": sets_kits.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/toys/sets_kits.png",
        "icon_class": "toys-category-icon--sets-kits",
        "category_code": sets_kits.SUBCATEGORY_CATEGORY_CODE,
        "category_code_by_tnved": sets_kits.CATEGORY_CODE_BY_TNVED,
        "allowed_tnved_codes": sets_kits.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": sets_kits.ALLOWED_TNVED_CHOICES,
        "allowed_tnved_codes_by_product_type": sets_kits.ALLOWED_TNVED_CODES_BY_PRODUCT_TYPE,
        "okpd2_choices_by_tnved": sets_kits.OKPD2_CHOICES_BY_TNVED,
        "model_article_types": sets_kits.MODEL_ARTICLE_TYPES,
        "product_types": sets_kits.PRODUCT_TYPES,
        "material_choices": sets_kits.MATERIAL_CHOICES,
        "min_child_age_choices": sets_kits.MIN_CHILD_AGE_CHOICES,
        "usage_term_types": sets_kits.USAGE_TERM_TYPES,
        "service_life_types": sets_kits.SERVICE_LIFE_TYPES,
        "default_countries": sets_kits.DEFAULT_COUNTRIES,
        "step_2_template": "helpers/toys/doll_accessories/2nd_step.html",
        "step_3_template": "helpers/toys/doll_accessories/3rd_step.html",
    },
    motorized_toys.SUBCATEGORY_SLUG: {
        "slug": motorized_toys.SUBCATEGORY_SLUG,
        "title": motorized_toys.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/toys/motorized_toys.png",
        "icon_class": "toys-category-icon--motorized-toys",
        "category_code": motorized_toys.SUBCATEGORY_CATEGORY_CODE,
        "category_code_by_tnved": motorized_toys.CATEGORY_CODE_BY_TNVED,
        "allowed_tnved_codes": motorized_toys.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": motorized_toys.ALLOWED_TNVED_CHOICES,
        "allowed_tnved_codes_by_product_type": motorized_toys.ALLOWED_TNVED_CODES_BY_PRODUCT_TYPE,
        "okpd2_choices_by_tnved": motorized_toys.OKPD2_CHOICES_BY_TNVED,
        "model_article_types": motorized_toys.MODEL_ARTICLE_TYPES,
        "product_types": motorized_toys.PRODUCT_TYPES,
        "drive_type_choices": motorized_toys.DRIVE_TYPE_CHOICES,
        "material_choices": motorized_toys.MATERIAL_CHOICES,
        "min_child_age_choices": motorized_toys.MIN_CHILD_AGE_CHOICES,
        "usage_term_types": motorized_toys.USAGE_TERM_TYPES,
        "service_life_types": motorized_toys.SERVICE_LIFE_TYPES,
        "default_countries": motorized_toys.DEFAULT_COUNTRIES,
        "step_2_template": "helpers/toys/doll_accessories/2nd_step.html",
        "step_3_template": "helpers/toys/doll_accessories/3rd_step.html",
    },
    animal_creature.SUBCATEGORY_SLUG: {
        "slug": animal_creature.SUBCATEGORY_SLUG,
        "title": animal_creature.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/toys/animal_creature.png",
        "icon_class": "toys-category-icon--animal-creature",
        "category_code": animal_creature.SUBCATEGORY_CATEGORY_CODE,
        "category_code_by_tnved": animal_creature.CATEGORY_CODE_BY_TNVED,
        "allowed_tnved_codes": animal_creature.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": animal_creature.ALLOWED_TNVED_CHOICES,
        "allowed_tnved_codes_by_product_type": animal_creature.ALLOWED_TNVED_CODES_BY_PRODUCT_TYPE,
        "okpd2_choices_by_tnved": animal_creature.OKPD2_CHOICES_BY_TNVED,
        "model_article_types": animal_creature.MODEL_ARTICLE_TYPES,
        "product_types": animal_creature.PRODUCT_TYPES,
        "drive_type_choices": animal_creature.DRIVE_TYPE_CHOICES,
        "material_choices": animal_creature.MATERIAL_CHOICES,
        "min_child_age_choices": animal_creature.MIN_CHILD_AGE_CHOICES,
        "usage_term_types": animal_creature.USAGE_TERM_TYPES,
        "service_life_types": animal_creature.SERVICE_LIFE_TYPES,
        "default_countries": animal_creature.DEFAULT_COUNTRIES,
        "step_2_template": "helpers/toys/doll_accessories/2nd_step.html",
        "step_3_template": "helpers/toys/doll_accessories/3rd_step.html",
    },
    scale_models_other.SUBCATEGORY_SLUG: {
        "slug": scale_models_other.SUBCATEGORY_SLUG,
        "title": scale_models_other.SUBCATEGORY_TITLE,
        "icon": "main_v2/img/icons/toys/scale_models_other_plastic.png",
        "icon_class": "toys-category-icon--scale-models",
        "category_code": scale_models_other.SUBCATEGORY_CATEGORY_CODE,
        "category_code_by_tnved": scale_models_other.CATEGORY_CODE_BY_TNVED,
        "allowed_tnved_codes": scale_models_other.ALLOWED_TNVED_CODES,
        "allowed_tnved_choices": scale_models_other.ALLOWED_TNVED_CHOICES,
        "allowed_tnved_codes_by_product_type": scale_models_other.ALLOWED_TNVED_CODES_BY_PRODUCT_TYPE,
        "okpd2_choices_by_tnved": scale_models_other.OKPD2_CHOICES_BY_TNVED,
        "model_article_types": scale_models_other.MODEL_ARTICLE_TYPES,
        "product_types": scale_models_other.PRODUCT_TYPES,
        "material_choices": scale_models_other.MATERIAL_CHOICES,
        "min_child_age_choices": scale_models_other.MIN_CHILD_AGE_CHOICES,
        "usage_term_types": scale_models_other.USAGE_TERM_TYPES,
        "service_life_types": scale_models_other.SERVICE_LIFE_TYPES,
        "default_countries": scale_models_other.DEFAULT_COUNTRIES,
        "step_2_template": "helpers/toys/doll_accessories/2nd_step.html",
        "step_3_template": "helpers/toys/doll_accessories/3rd_step.html",
    },
}


def get_subcategory_config(subcategory: str | None) -> dict | None:
    if not subcategory:
        return None
    return SUBCATEGORY_CONFIG.get(subcategory)
